version: '3'
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 80:3000
    volumes:
      - .:/app
  pg:
    image: postgres:10.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=phishin
  adminer:
    image: adminer
    ports:
      - 81:8080
