version: '3'

services:
  app:
    build: .
    ports:
      - 80:80
    volumes:
      - /private/var/app_content/phishin:/content
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@pg/phishin?pool=5
    tty: true
    stdin_open: true
  pg:
    image: postgres:10.5
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  adminer:
    image: adminer
    ports:
      - 81:8080

volumes:
  pg_data:
