version: '3'
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 80:3000
    volumes:
      - .:/app
      - /htdocs/app_content/phishin:/content
    tty: true
    stdin_open: true
  pg:
    image: postgres:10.4
    volumes:
      - pg_data:/var/lib/postgresql/data
      # - ./sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=phishin
  adminer:
    image: adminer
    ports:
      - 81:8080
volumes:
  pg_data: